export class UrlData {
  public urls = [
    ['1 Nephi 1:1 (1)', '1-ne/1.1.1'],
    ['Ex. 24:13 ', 'ex/24.13'],
    ['Ex 24:13 ', 'ex/24.13'],
    ['Exodus 28:1', 'ex/28.1'],
    ['Num. 4:12, 47', 'num/4.12,47'],
    ['Num 4:12, 47', 'num/4.12,47'],
    ['Numbers 4:12, 47', 'num/4.12,47'],
    ['Acts 1:25', 'acts/1.25'],
    ['1 Ne. 9:3–4', '1-ne/9.3-4'],
    ['1 Nephi 9:3–4', '1-ne/9.3-4'],
    ['1 Ne. 9:3-4', '1-ne/9.3-4'],
    ['1 Nephi 9:3-4', '1-ne/9.3-4'],
    ['3 Ne 10:19', '3-ne/10.19'],
    ['Abraham 2:9-11, 15-16, 23 (9-24)', 'abr/2.9-11,15-16,23.9-24'],
    ['Abr 2:9–11, 15–16, 23 (9–24)', 'abr/2.9-11,15-16,23.9-24'],
    ['Hosea 12:10 (9–11)', 'hosea/12.10.9-11'],
    ['Hosea 12:10 (9-11)', 'hosea/12.10.9-11'],
    ['sections137', 'dc/137'],
    ['Doctrine and Covenants 45:60–61', 'dc/45.60-61'],
    ['Alma 12:30', 'alma/12.30'],
    ['Moses 1:42', 'moses/1.42'],
    ['Ex. 19:3', 'ex/19.3'],
    ['Ezek. 40:2', 'ezek/40.2'],
    ['Rev. 21:10', 'rev/21.10'],
    ['Moses 1:42', 'moses/1.42'],
    ['Ex. 3:6', 'ex/3.6'],
    ['John 1:18', 'john/1.18'],
    ['Ether 3:15', 'ether/3.15'],
    ['Moses 1:11', 'moses/1.11'],

    ['Num. 12:8', 'num/12.8'],
    ['Deut. 34:10', 'deut/34.10'],
    ['D&amp;C 17:1', 'dc/17.1'],

    ['Ex. 25:1', 'ex/25.1'],

    ['Deut. 5:24', 'deut/5.24'],
    ['Moses 1:14 (13–14, 25)', 'moses/1.14.13-14,25'],

    ['Rev. 19:6', 'rev/19.6'],

    ['Isa. 63:16', 'isa/63.16'],
    ['D&amp;C 19:10 (9–12)', 'dc/19.10.9-12'],
    ['Moses 7:35', 'moses/7.35'],

    ['Ex. 3:15', 'ex/3.15'],
    ['Moses 7:4', 'moses/7.4'],
    ['Job 9:12', 'job/9.12'],
    ['Moses 7:32 (32–37)', 'moses/7.32.32-37'],
    ['Ps. 40:5', 'ps/40.5'],
    ['Morm. 9:16 (16–20)', 'morm/9.16.16-20'],
    ['D&amp;C 76:114', 'dc/76.114'],

    ['Ps. 111:8 (7–8)', 'ps/111.8.7-8'],
    ['1 Ne. 14:7', '1-ne/14.7']

    // ['D&amp;C 29:33', 'dc/29.33'-
    // ['TG God, Privilege of Seeing', 'tg/god-privilege-of-seeing'],
    // [
    //   'TG Jesus Christ, Appearances, Antemortal',
    //   'tg/jesus-christ-appearances-antemortal'
    // ],
    // ['TG Vision', 'tg/vision'],
    // ['TG God, Manifestations of', 'tg/god-manifestations-of'],
    // ['TG Communication', 'tg/communication'],
    // ['TG Glory', 'tg/glory'],
    // ['TG God, Glory of', 'tg/god-glory-of'],
    // ['TG Transfiguration', 'tg/transfiguration'],
    // ['TG Jesus Christ, Power of', 'tg/jesus-christ-power-of'],
    // ['TG God, Eternal Nature of', 'tg/god-eternal-nature-of'],
    // ['TG God, Power of', 'tg/god-power-of'],
    // ['TG God, Works of', 'tg/god-works-of'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Jesus Christ, Glory of', 'tg/jesus-christ-glory-of'],
    // ['TG God, Privilege of Seeing', 'tg/god-privilege-of-seeing'],
    // ['TG Celestial Glory', 'tg/celestial-glory'],
    // ['TG Jesus Christ, Savior', 'tg/jesus-christ-savior'],
    // ['TG Grace', 'tg/grace'],
    // ['TG God, Foreknowledge of', 'tg/god-foreknowledge-of'],
    // ['TG God, Omniscience of', 'tg/god-omniscience-of'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Mortality', 'tg/mortality'],
    // ['TG Humility', 'tg/humility'],
    // ['TG God, Privilege of Seeing', 'tg/god-privilege-of-seeing'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Transfiguration', 'tg/transfiguration'],
    // ['TG Devil', 'tg/devil'],
    // ['TG Glory', 'tg/glory'],
    // ['TG God, Spirit of', 'tg/god-spirit-of'],
    // ['TG Worship', 'tg/worship'],
    // ['TG God, Body of, Corporeal Nature', 'tg/god-body-of-corporeal-nature'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Jesus Christ, Glory of', 'tg/jesus-christ-glory-of'],
    // ['TG False Christs', 'tg/false-christs'],
    // ['TG Fearful', 'tg/fearful'],
    // ['TG Hell', 'tg/hell'],
    // ['TG Prayer', 'tg/prayer'],
    // ['TG God, Power of', 'tg/god-power-of'],
    // ['TG Strength', 'tg/strength'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Spirits, Evil or Unclean', 'tg/spirits-evil-or-unclean'],
    // ['TG Record Keeping', 'tg/record-keeping'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Priesthood, Authority', 'tg/priesthood-authority'],
    // ['TG Walking with God', 'tg/walking-with-god'],
    // ['TG Israel, Deliverance of', 'tg/israel-deliverance-of'],
    // ['TG Israel, Bondage of, in Egypt', 'tg/israel-bondage-of-in-egypt'],
    // ['TG Israel, Twelve Tribes of', 'tg/israel-twelve-tribes-of'],
    // ['TG Vision', 'tg/vision'],
    // ['TG Discernment, Spiritual', 'tg/discernment-spiritual'],
    // ['TG Holy Ghost, Mission of', 'tg/holy-ghost-mission-of'],
    // ['TG God, Spirit of', 'tg/god-spirit-of'],
    // ['TG Earth, Dividing of', 'tg/earth-dividing-of'],
    // ['TG Earth, Purpose of', 'tg/earth-purpose-of'],
    // ['TG God, Intelligence of', 'tg/god-intelligence-of'],
    // ['TG Jesus Christ, Authority of', 'tg/jesus-christ-authority-of'],
    // ['TG Grace', 'tg/grace'],
    // ['TG Astronomy', 'tg/astronomy'],
    // ['TG Creation', 'tg/creation'],
    // ['TG God, Works of', 'tg/god-works-of'],
    // ['TG World', 'tg/world'],
    // ['TG God, Creator', 'tg/god-creator'],
    // ['TG Jesus Christ, Divine Sonship', 'tg/jesus-christ-divine-sonship'],
    // ['TG Jesus Christ, Jehovah', 'tg/jesus-christ-jehovah'],
    // ['TG Jesus Christ, Creator', 'tg/jesus-christ-creator'],
    // ['TG Adam', 'tg/adam'],
    // ['TG God, Omniscience of', 'tg/god-omniscience-of'],
    // ['TG Heaven', 'tg/heaven'],
    // ['TG God, Works of', 'tg/god-works-of'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Jesus Christ, Glory of', 'tg/jesus-christ-glory-of'],
    // ['TG Immortality', 'tg/immortality'],
    // ['TG Jesus Christ, Mission of', 'tg/jesus-christ-mission-of'],
    // ['TG Resurrection', 'tg/resurrection'],
    // ['TG Eternal Life', 'tg/eternal-life'],
    // [
    //   'TG Man, Potential to Become like Heavenly Father',
    //   'tg/man-potential-to-become-like-heavenly-father'
    // ],
    // ['TG Earth, Purpose of', 'tg/earth-purpose-of'],
    // ['GS Moses', 'gs/moses'],
    // ['GS Glory', 'gs/glory'],
    // ['GS Transfiguration', 'gs/transfiguration'],
    // ['GS God, Godhead', 'gs/god-godhead'],
    // ['GS Endless', 'gs/endless'],
    // ['GS Word of God', 'gs/word-of-god'],
    // ['GS Only Begotten', 'gs/only-begotten'],
    // ['GS Savior', 'gs/savior'],
    // ['GS Grace', 'gs/grace'],
    // ['GS Omniscient', 'gs/omniscient'],
    // ['GS God, Godhead', 'gs/god-godhead'],
    // ['GS Transfiguration', 'gs/transfiguration'],
    // ['GS Devil', 'gs/devil'],
    // ['GS Tempt, Temptation', 'gs/tempt-temptation'],
    // ['GS Transfiguration', 'gs/transfiguration'],
    // ['GS Worship', 'gs/worship'],
    // ['GS Hell', 'gs/hell'],
    // ['GS Prayer', 'gs/prayer'],
    // ['GS Devil', 'gs/devil'],
    // ['GS Holy Ghost', 'gs/holy-ghost'],
    // ['GS Power', 'gs/power'],
    // ['GS Priesthood', 'gs/priesthood'],
    // ['GS Israel', 'gs/israel'],
    // ['GS Chosen (adjective or noun)', 'gs/chosen-adjective-or-noun'],
    // ['GS Vision', 'gs/vision'],
    // ['GS Earth', 'gs/earth'],
    // ['GS Jesus Christ', 'gs/jesus-christ'],
    // ['GS Grace', 'gs/grace'],
    // ['GS Truth', 'gs/truth'],
    // ['GS Create, Creation', 'gs/create-creation'],
    // ['GS Adam', 'gs/adam'],
    // ['GS Omniscient', 'gs/omniscient'],
    // ['GS Heaven', 'gs/heaven'],
    // ['GS Plan of Redemption', 'gs/plan-of-redemption'],
    // ['GS Glory', 'gs/glory'],
    // ['GS Immortal, Immortality', 'gs/immortal-immortality'],
    // ['GS Eternal Life', 'gs/eternal-life'],
    // ['TG Heaven', 'tg/heaven'],
    // ['TG Record Keeping', 'tg/record-keeping'],
    // ['TG Scribe', 'tg/scribe'],
    // ['TG Scriptures, Writing of', 'tg/scriptures-writing-of'],
    // ['TG Creation', 'tg/creation'],
    // ['TG Jesus Christ, Creator', 'tg/jesus-christ-creator'],
    // ['TG God, Creator', 'tg/god-creator'],
    // ['TG God, Works of', 'tg/god-works-of'],
    // ['TG Darkness, Physical', 'tg/darkness-physical'],
    // ['TG God, Spirit of', 'tg/god-spirit-of'],
    // ['TG Light [noun]', 'tg/light-noun'],
    // ['TG Light [noun]', 'tg/light-noun'],
    // ['TG Earth, Dividing of', 'tg/earth-dividing-of'],
    // ['TG Light [noun]', 'tg/light-noun'],
    // ['TG Astronomy', 'tg/astronomy'],
    // ['TG Darkness, Physical', 'tg/darkness-physical'],
    // ['TG Jesus Christ, Divine Sonship', 'tg/jesus-christ-divine-sonship'],
    // ['TG Jesus Christ, Firstborn', 'tg/jesus-christ-firstborn'],
    // ['TG Jesus Christ, Creator', 'tg/jesus-christ-creator'],
    // ['TG Man, Physical Creation of', 'tg/man-physical-creation-of'],
    // ['TG God, Body of, Corporeal Nature', 'tg/god-body-of-corporeal-nature'],
    // ['TG Birth Control', 'tg/birth-control'],
    // ['TG Marriage, Fatherhood', 'tg/marriage-fatherhood'],
    // ['GS Heaven', 'gs/heaven'],
    // ['GS God, Godhead—God the Father', 'gs/god-godhead/god-the-father'],
    // ['GS Only Begotten', 'gs/only-begotten'],
    // ['GS Create, Creation', 'gs/create-creation'],
    // ['GS Light, Light of Christ', 'gs/light-light-of-christ'],
    // ['GS Heaven', 'gs/heaven'],
    // ['GS Earth', 'gs/earth'],
    // ['GS Jesus Christ', 'gs/jesus-christ'],
    // ['GS Create, Creation', 'gs/create-creation'],
    // ['GS God, Godhead', 'gs/god-godhead'],
    // ['TG Creation', 'tg/creation'],
    // ['TG Rest', 'tg/rest'],
    // ['TG Sabbath', 'tg/sabbath'],
    // ['TG Creation', 'tg/creation'],
    // ['TG God, Creator', 'tg/god-creator'],
    // ['TG Life, Sanctity of', 'tg/life-sanctity-of'],
    // ['TG Spirit Creation', 'tg/spirit-creation'],
    // ['TG Man, Physical Creation of', 'tg/man-physical-creation-of'],
    // [
    //   'TG Man, a Spirit Child of Heavenly Father',
    //   'tg/man-a-spirit-child-of-heavenly-father'
    // ],
    // ['TG Heaven', 'tg/heaven'],
    // ['TG Man, Antemortal Existence of', 'tg/man-antemortal-existence-of'],
    // ['TG Breath of Life', 'tg/breath-of-life'],
    // ['TG Adam', 'tg/adam'],
    // ['TG Soul', 'tg/soul'],
    // ['TG Eden', 'tg/eden'],
    // ['TG Life, Sanctity of', 'tg/life-sanctity-of'],
    // ['TG Eden', 'tg/eden'],
    // ['TG Eden', 'tg/eden'],
    // ['TG Knowledge', 'tg/knowledge'],
    // ['TG Agency', 'tg/agency'],
    // ['TG Mortality', 'tg/mortality'],
    // ['TG Jesus Christ, Divine Sonship', 'tg/jesus-christ-divine-sonship'],
    // ['TG Family, Eternal', 'tg/family-eternal'],
    // ['TG Creation', 'tg/creation'],
    // ['TG Breath of Life', 'tg/breath-of-life'],
    // ['TG Language', 'tg/language'],
    // ['TG Creation', 'tg/creation'],
    // ['TG Woman', 'tg/woman'],
    // ['TG Adam', 'tg/adam'],
    // ['TG Family, Love within', 'tg/family-love-within'],
    // ['TG Divorce', 'tg/divorce'],
    // ['TG Marriage, Celestial', 'tg/marriage-celestial'],
    // ['GS Create, Creation', 'gs/create-creation'],
    // ['GS Rest', 'gs/rest'],
    // ['GS Sabbath Day', 'gs/sabbath-day'],
    // ['GS Spirit Creation', 'gs/spirit-creation'],
    // ['GS Spirit', 'gs/spirit'],
    // ['GS Heaven', 'gs/heaven'],
    //    [
    //      'GS Man, Men—Man, a spirit child of Heavenly Father',
    //      'gs/man-men/man-a-spirit-child-of-heavenly-father'
    //    ],
    // ['GS Adam', 'gs/adam'],
    // ['GS Soul', 'gs/soul'],
    // ['GS Eden', 'gs/eden'],
    // ['GS Tree of Life', 'gs/tree-of-life'],
    // ['GS Agency', 'gs/agency'],
    // ['GS Death, Physical', 'gs/death-physical'],
    // ['GS Mortal, Mortality', 'gs/mortal-mortality'],
    // ['GS Only Begotten', 'gs/only-begotten'],
    // ['GS Eve', 'gs/eve'],
    // ['GS Woman, Women', 'gs/woman-women'],
    // ['GS Marriage, Marry', 'gs/marriage-marry'],
    // ['TG Redemption', 'tg/redemption'],
    // ['TG Selfishness', 'tg/selfishness'],
    // ['TG Jesus Christ, Divine Sonship', 'tg/jesus-christ-divine-sonship'],
    // ['TG Witness of the Father', 'tg/witness-of-the-father'],
    // ['TG Foreordination', 'tg/foreordination'],
    // ['TG Jesus Christ, Authority of', 'tg/jesus-christ-authority-of'],
    // ['TG Jesus Christ, Foreordained', 'tg/jesus-christ-foreordained'],
    // [
    //   'TG Jesus Christ, Messenger of the Covenant',
    //   'tg/jesus-christ-messenger-of-the-covenant'
    // ],
    // ['TG Jesus Christ, Messiah', 'tg/jesus-christ-messiah'],
    // ['TG God the Father, Elohim', 'tg/god-the-father-elohim'],
    // [
    //   'TG God, the Standard of Righteousness',
    //   'tg/god-the-standard-of-righteousness'
    // ],
    // ['TG Glory', 'tg/glory'],
    // ['TG Sons of Perdition', 'tg/sons-of-perdition'],
    // ['TG Council in Heaven', 'tg/council-in-heaven'],
    // ['TG Rebellion', 'tg/rebellion'],
    // ['TG Agency', 'tg/agency'],
    // ['TG Devil', 'tg/devil'],
    // ['TG Honesty', 'tg/honesty'],
    // ['TG Lying', 'tg/lying'],
    // ['TG Deceit', 'tg/deceit'],
    // ['TG Bondage, Spiritual', 'tg/bondage-spiritual'],
    // ['TG Disobedience', 'tg/disobedience'],
    // ['TG Devil', 'tg/devil'],
    // ['TG Honesty', 'tg/honesty'],
    // ['TG Mind', 'tg/mind'],
    // ['TG Knowledge', 'tg/knowledge'],
    // ['TG Fall of Man', 'tg/fall-of-man'],
    // ['TG Apparel', 'tg/apparel'],
    // ['TG Pain', 'tg/pain'],
    // ['TG Marriage, Husbands', 'tg/marriage-husbands'],
    // ['TG Marriage, Wives', 'tg/marriage-wives'],
    // ['TG Earth, Curse of', 'tg/earth-curse-of'],
    // ['TG Suffering', 'tg/suffering'],
    // ['TG Mortality', 'tg/mortality'],
    // ['TG Apparel', 'tg/apparel'],
    // ['TG Clothing', 'tg/clothing'],
    // ['TG Modesty', 'tg/modesty'],
    // [
    //   'TG Man, Potential to Become like Heavenly Father',
    //   'tg/man-potential-to-become-like-heavenly-father'
    // ],
    // ['TG Knowledge', 'tg/knowledge'],
    // ['TG Probation', 'tg/probation'],
    // ['TG Eden', 'tg/eden'],
    // ['TG Eden', 'tg/eden'],
    // ['TG Cherubim', 'tg/cherubim'],
    // ['GS Devil', 'gs/devil'],
    // ['GS Jesus Christ', 'gs/jesus-christ'],
    // ['GS Foreordination', 'gs/foreordination'],
    // ['GS God, Godhead—God the Father', 'gs/god-godhead/god-the-father'],
    // ['GS Glory', 'gs/glory'],
    // ['GS Council in Heaven', 'gs/council-in-heaven'],
    // ['GS Agency', 'gs/agency'],
    // ['GS Deceit, Deceive, Deception', 'gs/deceit-deceive-deception'],
    // ['GS Lying', 'gs/lying'],
    // ['GS Eve', 'gs/eve'],
    // ['GS Eden', 'gs/eden'],
    // ['GS Fall of Adam and Eve', 'gs/fall-of-adam-and-eve'],
    // ['GS Fall of Adam and Eve', 'gs/fall-of-adam-and-eve'],
    // ['GS Modesty', 'gs/modesty'],
    //    [
    //      'GS Man, Men—Man, potential to become like Heavenly Father',
    //      'gs/man-men/man-potential-to-become-like-heavenly-father'
    //    ],
    // ['GS Knowledge', 'gs/knowledge'],
    // ['GS Tree of Life', 'gs/tree-of-life'],
    // ['GS Eden', 'gs/eden'],
    // ['GS Cherubim', 'gs/cherubim'],
    // ['TG Labor', 'tg/labor'],
    // ['TG Eden', 'tg/eden'],
    // ['TG Worship', 'tg/worship'],
    // ['TG Firstborn', 'tg/firstborn'],
    // ['TG Obedience', 'tg/obedience'],
    // ['TG Angels', 'tg/angels'],
    // ['TG Ordinance', 'tg/ordinance'],
    // ['TG Sacrifice', 'tg/sacrifice'],
    // [
    //   'TG Jesus Christ, Types of, in Anticipation',
    //   'tg/jesus-christ-types-of-in-anticipation'
    // ],
    // ['TG Blood, Symbolism of', 'tg/blood-symbolism-of'],
    // ['TG Jesus Christ, Atonement through', 'tg/jesus-christ-atonement-through'],
    // ['TG Grace', 'tg/grace'],
    // ['TG Repent', 'tg/repent'],
    // ['TG Prayer', 'tg/prayer'],
    // ['TG Holy Ghost, Baptism of', 'tg/holy-ghost-baptism-of'],
    // ['TG Jesus Christ, Divine Sonship', 'tg/jesus-christ-divine-sonship'],
    // ['TG Death, Spiritual, First', 'tg/death-spiritual-first'],
    // ['TG Fall of Man', 'tg/fall-of-man'],
    // ['TG Redemption', 'tg/redemption'],
    // ['TG Salvation, Plan of', 'tg/salvation-plan-of'],
    // ['TG Man, New, Spiritually Reborn', 'tg/man-new-spiritually-reborn'],
    // ['TG Transgress', 'tg/transgress'],
    // ['TG Joy', 'tg/joy'],
    // ['TG Birth Control', 'tg/birth-control'],
    // ['TG Family', 'tg/family'],
    // ['TG Marriage, Motherhood', 'tg/marriage-motherhood'],
    // ['TG Devil', 'tg/devil'],
    // ['TG Spiritual Blindness', 'tg/spiritual-blindness'],
    // ['TG Unbelief', 'tg/unbelief'],
    // ['TG Carnal Mind', 'tg/carnal-mind'],
    // [
    //   'TG Man, Natural, Not Spiritually Reborn',
    //   'tg/man-natural-not-spiritually-reborn'
    // ],
    // ['TG Faith', 'tg/faith'],
    // ['TG Jesus Christ, Savior', 'tg/jesus-christ-savior'],
    // ['TG Respect', 'tg/respect'],
    // ['TG Sacrifice', 'tg/sacrifice'],
    // ['TG Bondage, Spiritual', 'tg/bondage-spiritual'],
    // ['TG Honesty', 'tg/honesty'],
    // ['TG Sons of Perdition', 'tg/sons-of-perdition'],
    // ['TG Curse', 'tg/curse'],
    // ['TG Mourning', 'tg/mourning'],
    // ['TG Murder', 'tg/murder'],
    // ['TG Boast', 'tg/boast'],
    // ['TG Covet', 'tg/covet'],
    // ['TG Life, Sanctity of', 'tg/life-sanctity-of'],
    // ['TG Curse', 'tg/curse'],
    // ['TG Strength', 'tg/strength'],
    // ['TG Covet', 'tg/covet'],
    // ['TG Temptation', 'tg/temptation'],
    // ['TG Punish', 'tg/punish'],
    // ['TG Bondage, Spiritual', 'tg/bondage-spiritual'],
    // ['TG Oath', 'tg/oath'],
    // ['TG Secret Combinations', 'tg/secret-combinations'],
    // ['TG Curse', 'tg/curse'],
    // ['TG Darkness, Spiritual', 'tg/darkness-spiritual'],
    // ['TG Earth, Curse of', 'tg/earth-curse-of'],
    // ['TG Disobedience', 'tg/disobedience'],
    // ['TG Unbelief', 'tg/unbelief'],
    // ['TG Jesus Christ, Birth of', 'tg/jesus-christ-birth-of'],
    // ['TG Jesus Christ, Authority of', 'tg/jesus-christ-authority-of'],
    // ['TG Gospel', 'tg/gospel'],
    // ['TG Preaching', 'tg/preaching'],
    // ['TG Adam', 'tg/adam'],
    // ['GS Eden', 'gs/eden'],
    // ['GS Worship', 'gs/worship'],
    // ['GS Firstborn', 'gs/firstborn'],
    // ['GS Obedience, Obedient, Obey', 'gs/obedience-obedient-obey'],
    // ['GS Angels', 'gs/angels'],
    // ['GS Sacrifice', 'gs/sacrifice'],
    //    [
    //      'GS Jesus Christ—Types or symbols of Christ',
    //      'gs/jesus-christ/types-or-symbols-of-christ'
    //    ],
    // ['GS Blood', 'gs/blood'],
    // ['GS Grace', 'gs/grace'],
    // ['GS Repent, Repentance', 'gs/repent-repentance'],
    // ['GS Prayer', 'gs/prayer'],
    // ['GS Holy Ghost', 'gs/holy-ghost'],
    // ['GS Jesus Christ', 'gs/jesus-christ'],
    // ['GS Only Begotten', 'gs/only-begotten'],
    // ['GS Death, Spiritual', 'gs/death-spiritual'],
    // ['GS Fall of Adam and Eve', 'gs/fall-of-adam-and-eve'],
    // ['GS Plan of Redemption', 'gs/plan-of-redemption'],
    // ['GS Redeem, Redeemed, Redemption', 'gs/redeem-redeemed-redemption'],
    // ['GS Born Again, Born of God', 'gs/born-again-born-of-god'],
    // ['GS Prophecy, Prophesy', 'gs/prophecy-prophesy'],
    // ['GS Joy', 'gs/joy'],
    // ['GS Eve', 'gs/eve'],
    // ['GS Devil', 'gs/devil'],
    // ['GS Unbelief', 'gs/unbelief'],
    // ['GS Carnal', 'gs/carnal'],
    // ['GS Natural Man', 'gs/natural-man'],
    // ['GS Belief, Believe', 'gs/belief-believe'],
    // ['GS Salvation', 'gs/salvation'],
    // ['GS Damnation', 'gs/damnation'],
    // ['GS Cain', 'gs/cain'],
    // ['GS Abel', 'gs/abel'],
    // ['GS Offering', 'gs/offering'],
    // ['GS Sacrifice', 'gs/sacrifice'],
    // ['GS Sons of Perdition', 'gs/sons-of-perdition'],
    // ['GS Murder', 'gs/murder'],
    // ['GS Pride', 'gs/pride'],
    // ['GS Worldliness', 'gs/worldliness'],
    // ['GS Covet', 'gs/covet'],
    // ['GS Tempt, Temptation', 'gs/tempt-temptation'],
    // ['GS Oath', 'gs/oath'],
    // ['GS Secret Combinations', 'gs/secret-combinations'],
    // ['GS Darkness, Spiritual', 'gs/darkness-spiritual'],
    // ['GS Wicked, Wickedness', 'gs/wicked-wickedness'],
    // ['GS Jesus Christ', 'gs/jesus-christ'],
    // ['GS Gospel', 'gs/gospel'],
    // ['GS Angels', 'gs/angels'],
    // ['GS Gift of the Holy Ghost', 'gs/gift-of-the-holy-ghost'],
    // ['TG Sacrifice', 'tg/sacrifice'],
    // ['TG Prayer', 'tg/prayer'],
    // ['TG Scriptures, Lost', 'tg/scriptures-lost'],
    // ['TG Scriptures, Writing of', 'tg/scriptures-writing-of'],
    // ['TG Book of Remembrance', 'tg/book-of-remembrance'],
    // ['TG Guidance, Divine', 'tg/guidance-divine'],
    // ['TG Inspiration', 'tg/inspiration'],
    // ['TG Education', 'tg/education'],
    // [
    //   'TG Family, Children, Responsibilities toward',
    //   'tg/family-children-responsibilities-toward'
    // ],
    // ['TG Language', 'tg/language'],
    // ['TG Priesthood', 'tg/priesthood'],
    // ['TG Priesthood, History of', 'tg/priesthood-history-of'],
    // ['TG Priesthood, Melchizedek', 'tg/priesthood-melchizedek'],
    // ['TG Genealogy and Temple Work', 'tg/genealogy-and-temple-work'],
    // ['TG Sons and Daughters of God', 'tg/sons-and-daughters-of-god'],
    // ['TG God, Body of, Corporeal Nature', 'tg/god-body-of-corporeal-nature'],
    // ['TG Man, Physical Creation of', 'tg/man-physical-creation-of'],
    // ['TG Soul', 'tg/soul'],
    // ['TG War', 'tg/war'],
    // ['TG Conspiracy', 'tg/conspiracy'],
    // ['TG Secret Combinations', 'tg/secret-combinations'],
    // ['TG Selfishness', 'tg/selfishness'],
    // ['TG Preaching', 'tg/preaching'],
    // ['TG Righteousness', 'tg/righteousness'],
    // ['TG Prophets, Mission of', 'tg/prophets-mission-of'],
    // ['TG Faith', 'tg/faith'],
    // ['TG Education', 'tg/education'],
    // ['TG God, Spirit of', 'tg/god-spirit-of'],
    // ['TG Guidance, Divine', 'tg/guidance-divine'],
    // ['TG Hardheartedness', 'tg/hardheartedness'],
    // ['TG Rebellion', 'tg/rebellion'],
    // ['TG Hell', 'tg/hell'],
    // ['TG Hate', 'tg/hate'],
    // ['TG Prophets, Mission of', 'tg/prophets-mission-of'],
    // ['TG Agency', 'tg/agency'],
    // ['TG Procrastination', 'tg/procrastination'],
    // ['TG Teaching with the Spirit', 'tg/teaching-with-the-spirit'],
    // ['TG Walking with God', 'tg/walking-with-god'],
    // ['TG Man, Antemortal Existence of', 'tg/man-antemortal-existence-of'],
    // ['TG Spirit Body', 'tg/spirit-body'],
    // ['TG Spirit Creation', 'tg/spirit-creation'],
    // ['TG Seer', 'tg/seer'],
    // ['TG God, Privilege of Seeing', 'tg/god-privilege-of-seeing'],
    // ['TG Walking with God', 'tg/walking-with-god'],
    // ['TG Righteousness', 'tg/righteousness'],
    // ['TG Adam', 'tg/adam'],
    // ['TG Book of Remembrance', 'tg/book-of-remembrance'],
    // ['TG Genealogy and Temple Work', 'tg/genealogy-and-temple-work'],
    // ['TG Scriptures, Writing of', 'tg/scriptures-writing-of'],
    // ['TG Fall of Man', 'tg/fall-of-man'],
    // ['TG Death', 'tg/death'],
    // ['TG Mortality', 'tg/mortality'],
    // ['TG Temptation', 'tg/temptation'],
    // ['TG Worship', 'tg/worship'],
    // ['TG Carnal Mind', 'tg/carnal-mind'],
    // [
    //   'TG Man, Natural, Not Spiritually Reborn',
    //   'tg/man-natural-not-spiritually-reborn'
    // ],
    // ['TG Sensuality', 'tg/sensuality'],
    // [
    //   'TG Man, a Spirit Child of Heavenly Father',
    //   'tg/man-a-spirit-child-of-heavenly-father'
    // ],
    // ['TG Spirit Creation', 'tg/spirit-creation'],
    // ['TG Baptism, Essential', 'tg/baptism-essential'],
    // ['TG Grace', 'tg/grace'],
    // ['TG Jesus Christ, Messiah', 'tg/jesus-christ-messiah'],
    // ['TG Jesus Christ, Authority of', 'tg/jesus-christ-authority-of'],
    // ['TG Name', 'tg/name'],
    // ['TG Jesus Christ, Savior', 'tg/jesus-christ-savior'],
    // ['TG Salvation', 'tg/salvation'],
    // ['TG Forgive', 'tg/forgive'],
    // ['TG Jesus Christ, Divine Sonship', 'tg/jesus-christ-divine-sonship'],
    // ['TG Jesus Christ, Atonement through', 'tg/jesus-christ-atonement-through'],
    // ['TG Children', 'tg/children'],
    // ['TG Salvation of Little Children', 'tg/salvation-of-little-children'],
    // ['TG Conceived in Sin', 'tg/conceived-in-sin'],
    // ['TG Death, Spiritual, First', 'tg/death-spiritual-first'],
    // [
    //   'TG Man, Natural, Not Spiritually Reborn',
    //   'tg/man-natural-not-spiritually-reborn'
    // ],
    // ['TG Opposition', 'tg/opposition'],
    // ['TG Agency', 'tg/agency'],
    // ['TG Baptism, Qualifications for', 'tg/baptism-qualifications-for'],
    // ['TG Repent', 'tg/repent'],
    // ['TG Chastity', 'tg/chastity'],
    // ['TG Cleanliness', 'tg/cleanliness'],
    // ['TG God, Perfection of', 'tg/god-perfection-of'],
    // ['TG Modesty', 'tg/modesty'],
    // ['TG Uncleanness', 'tg/uncleanness'],
    // ['TG God, Presence of', 'tg/god-presence-of'],
    // ['TG Jesus Christ, Prophecies about', 'tg/jesus-christ-prophecies-about'],
    // ['TG God, Justice of', 'tg/god-justice-of'],
    // ['TG Jesus Christ, Judge', 'tg/jesus-christ-judge'],
    // ['TG Authority', 'tg/authority'],
    // ['TG Education', 'tg/education'],
    // [
    //   'TG Family, Children, Responsibilities toward',
    //   'tg/family-children-responsibilities-toward'
    // ],
    // ['TG Holy Ghost, Baptism of', 'tg/holy-ghost-baptism-of'],
    // ['TG Man, New, Spiritually Reborn', 'tg/man-new-spiritually-reborn'],
    // ['TG Baptism', 'tg/baptism'],
    // ['TG Baptism, Essential', 'tg/baptism-essential'],
    // ['TG Celestial Glory', 'tg/celestial-glory'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Justification', 'tg/justification'],
    // ['TG Blood, Shedding of', 'tg/blood-shedding-of'],
    // ['TG Blood, Symbolism of', 'tg/blood-symbolism-of'],
    // ['TG Sanctification', 'tg/sanctification'],
    // ['TG Holy Ghost, Source of Testimony', 'tg/holy-ghost-source-of-testimony'],
    // ['TG Holy Ghost, Comforter', 'tg/holy-ghost-comforter'],
    // ['TG Peace of God', 'tg/peace-of-god'],
    // ['TG Jesus Christ, Power of', 'tg/jesus-christ-power-of'],
    // ['TG Gospel', 'tg/gospel'],
    // ['TG Salvation, Plan of', 'tg/salvation-plan-of'],
    // ['TG Blood, Symbolism of', 'tg/blood-symbolism-of'],
    // ['TG Jesus Christ, Birth of', 'tg/jesus-christ-birth-of'],
    // ['TG Holy Ghost, Mission of', 'tg/holy-ghost-mission-of'],
    // ['TG Baptism, Immersion', 'tg/baptism-immersion'],
    // ['TG Man, New, Spiritually Reborn', 'tg/man-new-spiritually-reborn'],
    // ['TG Priesthood, Melchizedek', 'tg/priesthood-melchizedek'],
    // ['TG Sons and Daughters of God', 'tg/sons-and-daughters-of-god'],
    // ['GS Adam', 'gs/adam'],
    // ['GS Seth', 'gs/seth'],
    // ['GS Sacrifice', 'gs/sacrifice'],
    // ['GS Prayer', 'gs/prayer'],
    // ['GS Book of Remembrance', 'gs/book-of-remembrance'],
    // ['GS Inspiration, Inspire', 'gs/inspiration-inspire'],
    // ['GS Priesthood', 'gs/priesthood'],
    // ['GS Genealogy', 'gs/genealogy'],
    // ['GS Sons and Daughters of God', 'gs/sons-and-daughters-of-god'],
    // ['GS Man, Men', 'gs/man-men'],
    // ['GS Soul', 'gs/soul'],
    // ['GS Secret Combinations', 'gs/secret-combinations'],
    // ['GS Enoch', 'gs/enoch'],
    // ['GS Prophet', 'gs/prophet'],
    // ['GS Prophecy, Prophesy', 'gs/prophecy-prophesy'],
    // ['GS Repent, Repentance', 'gs/repent-repentance'],
    // ['GS Faith', 'gs/faith'],
    // ['GS Methuselah', 'gs/methuselah'],
    // ['GS Rebellion', 'gs/rebellion'],
    // ['GS Oath', 'gs/oath'],
    // ['GS Hell', 'gs/hell'],
    // ['GS Agency', 'gs/agency'],
    // ['GS Walk, Walk with God', 'gs/walk-walk-with-god'],
    // ['GS Spirit Creation', 'gs/spirit-creation'],
    // ['GS Seer', 'gs/seer'],
    // ['GS Book of Remembrance', 'gs/book-of-remembrance'],
    // ['GS Fall of Adam and Eve', 'gs/fall-of-adam-and-eve'],
    // ['GS Death, Physical', 'gs/death-physical'],
    // ['GS Tempt, Temptation', 'gs/tempt-temptation'],
    // ['GS Carnal', 'gs/carnal'],
    // ['GS Sensual, Sensuality', 'gs/sensual-sensuality'],
    // ['GS Death, Spiritual', 'gs/death-spiritual'],
    //    [
    //      'GS Man, Men—Man, a spirit child of Heavenly Father',
    //      'gs/man-men/man-a-spirit-child-of-heavenly-father'
    //    ],
    // ['GS Spirit Creation', 'gs/spirit-creation'],
    // ['GS Baptism, Baptize', 'gs/baptism-baptize'],
    // ['GS Grace', 'gs/grace'],
    // ['GS Jesus Christ', 'gs/jesus-christ'],
    // ['GS Salvation', 'gs/salvation'],
    // ['GS Forgive', 'gs/forgive'],
    // ['GS Jesus Christ', 'gs/jesus-christ'],
    // ['GS Atone, Atonement', 'gs/atone-atonement'],
    // ['GS Sin', 'gs/sin'],
    // ['GS Adversity', 'gs/adversity'],
    // ['GS Agency', 'gs/agency'],
    // ['GS Repent, Repentance', 'gs/repent-repentance'],
    // ['GS Clean and Unclean', 'gs/clean-and-unclean'],
    // ['GS Man of Holiness', 'gs/man-of-holiness'],
    // ['GS Son of Man', 'gs/son-of-man'],
    // ['GS Jesus Christ—Judge', 'gs/jesus-christ/judge'],
    // ['GS Justice', 'gs/justice'],
    // ['GS Child, Children', 'gs/child-children'],
    // ['GS Born Again, Born of God', 'gs/born-again-born-of-god'],
    // ['GS Baptism, Baptize', 'gs/baptism-baptize'],
    // ['GS Celestial Glory', 'gs/celestial-glory'],
    // ['GS Justification, Justify', 'gs/justification-justify'],
    // ['GS Blood', 'gs/blood'],
    // ['GS Sanctification', 'gs/sanctification'],
    // ['GS Holy Ghost', 'gs/holy-ghost'],
    // ['GS Plan of Redemption', 'gs/plan-of-redemption'],
    // ['GS Only Begotten', 'gs/only-begotten'],
    // ['GS Holy Ghost', 'gs/holy-ghost'],
    // ['GS Baptism, Baptize', 'gs/baptism-baptize'],
    // ['GS Born Again, Born of God', 'gs/born-again-born-of-god'],
    // ['GS Gift of the Holy Ghost', 'gs/gift-of-the-holy-ghost'],
    // ['GS Melchizedek Priesthood', 'gs/melchizedek-priesthood'],
    // ['GS Sons and Daughters of God', 'gs/sons-and-daughters-of-god'],
    // ['TG Sons and Daughters of God', 'tg/sons-and-daughters-of-god'],
    // ['TG Transfiguration', 'tg/transfiguration'],
    // ['TG God, Privilege of Seeing', 'tg/god-privilege-of-seeing'],
    // [
    //   'TG Jesus Christ, Appearances, Antemortal',
    //   'tg/jesus-christ-appearances-antemortal'
    // ],
    // ['TG God, Omniscience of', 'tg/god-omniscience-of'],
    // ['TG Revelation', 'tg/revelation'],
    // ['TG Earth, Curse of', 'tg/earth-curse-of'],
    // ['TG Barren', 'tg/barren'],
    // ['TG Baptism, Essential', 'tg/baptism-essential'],
    // ['TG Grace', 'tg/grace'],
    // ['TG Faith', 'tg/faith'],
    // ['TG Priesthood, Power of', 'tg/priesthood-power-of'],
    // ['TG God, Presence of', 'tg/god-presence-of'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Zion', 'tg/zion'],
    // ['TG Unity', 'tg/unity'],
    // ['TG Jerusalem, New', 'tg/jerusalem-new'],
    // ['TG Heaven', 'tg/heaven'],
    // ['TG Vision', 'tg/vision'],
    // ['TG Angels', 'tg/angels'],
    // ['TG Testimony', 'tg/testimony'],
    // ['TG Astronomy', 'tg/astronomy'],
    // ['TG Creation', 'tg/creation'],
    // ['TG God, Justice of', 'tg/god-justice-of'],
    // ['TG God, Intelligence of', 'tg/god-intelligence-of'],
    // ['TG Knowledge', 'tg/knowledge'],
    // ['TG Agency', 'tg/agency'],
    // ['TG Love', 'tg/love'],
    // ['TG Hate', 'tg/hate'],
    // ['TG Flood', 'tg/flood'],
    // ['TG God, Omniscience of', 'tg/god-omniscience-of'],
    // ['TG Spirits in Prison', 'tg/spirits-in-prison'],
    // ['TG Damnation', 'tg/damnation'],
    // ['TG God, Omniscience of', 'tg/god-omniscience-of'],
    // ['TG Compassion', 'tg/compassion'],
    // ['TG Flood', 'tg/flood'],
    // ['TG Punish', 'tg/punish'],
    // ['TG Sanctification', 'tg/sanctification'],
    // [
    //   'TG Jesus Christ, Appearances, Antemortal',
    //   'tg/jesus-christ-appearances-antemortal'
    // ]
    // ['TG Jesus Christ, Lamb of God', 'tg/jesus-christ-lamb-of-god'],
    // ['TG Passover', 'tg/passover'],
    // ['TG Faith', 'tg/faith'],
    // ['TG Earth, Purpose of', 'tg/earth-purpose-of'],
    // ['TG Pain', 'tg/pain'],
    // ['TG Earth, Cleansing of', 'tg/earth-cleansing-of'],
    // ['TG Filthiness', 'tg/filthiness'],
    // ['TG Flood', 'tg/flood'],
    // ['TG Jesus Christ, Messiah', 'tg/jesus-christ-messiah'],
    // ['TG Cornerstone', 'tg/cornerstone'],
    // ['TG Rock', 'tg/rock'],
    // ['TG Eternity', 'tg/eternity'],
    // ['TG Singing', 'tg/singing'],
    // ['TG Joy', 'tg/joy'],
    // ['TG Jesus Christ, Prophecies about', 'tg/jesus-christ-prophecies-about'],
    // ['TG Jesus Christ, Crucifixion of', 'tg/jesus-christ-crucifixion-of'],
    // ['TG Veil', 'tg/veil'],
    // ['TG Saints', 'tg/saints'],
    // ['TG Exaltation', 'tg/exaltation'],
    // ['TG Spirits, Disembodied', 'tg/spirits-disembodied'],
    // ['TG Salvation for the Dead', 'tg/salvation-for-the-dead'],
    // ['TG Spirits in Prison', 'tg/spirits-in-prison'],
    // ['TG Last Days', 'tg/last-days'],
    // ['TG Rest', 'tg/rest'],
    // ['TG Veil', 'tg/veil'],
    // ['TG Protection, Divine', 'tg/protection-divine'],
    // ['TG Righteousness', 'tg/righteousness'],
    // ['TG Testimony', 'tg/testimony'],
    // ['TG Jesus Christ, Resurrection', 'tg/jesus-christ-resurrection'],
    // ['TG Israel, Gathering of', 'tg/israel-gathering-of'],
    // ['TG Zion', 'tg/zion'],
    // ['TG Jerusalem, New', 'tg/jerusalem-new'],
    // ['TG Millennium', 'tg/millennium'],
    // ['TG Earth, Destiny of', 'tg/earth-destiny-of'],
    // ['TG Earth, Purpose of', 'tg/earth-purpose-of'],
    // ['TG Judgment, the Last', 'tg/judgment-the-last'],
    // ['TG Joy', 'tg/joy'],
    // ['TG Walking with God', 'tg/walking-with-god'],
    // ['GS Sons and Daughters of God', 'gs/sons-and-daughters-of-god'],
    // ['GS Transfiguration', 'gs/transfiguration'],
    // ['GS Repent, Repentance', 'gs/repent-repentance'],
    // ['GS Baptism, Baptize', 'gs/baptism-baptize'],
    // ['GS Grace', 'gs/grace'],
    // ['GS Holy Ghost', 'gs/holy-ghost'],
    // ['GS Faith', 'gs/faith'],
    // ['GS Power', 'gs/power'],
    // ['GS Priesthood', 'gs/priesthood'],
    // ['GS Zion', 'gs/zion'],
    // ['GS Unity', 'gs/unity'],
    // ['GS New Jerusalem', 'gs/new-jerusalem'],
    // ['GS Heaven', 'gs/heaven'],
    // ['GS Vision', 'gs/vision'],
    // ['GS Angels', 'gs/angels'],
    // ['GS Testimony', 'gs/testimony'],
    // ['GS Create, Creation', 'gs/create-creation'],
    // ['GS Peace', 'gs/peace'],
    // ['GS Justice', 'gs/justice'],
    // ['GS Truth', 'gs/truth'],
    // ['GS Knowledge', 'gs/knowledge'],
    // ['GS Agency', 'gs/agency'],
    // ['GS Love', 'gs/love'],
    // ['GS Flood at Noah’s Time', 'gs/flood-at-noahs-time'],
    // ['GS Hell', 'gs/hell'],
    // ['GS Jesus Christ', 'gs/jesus-christ'],
    // ['GS Damnation', 'gs/damnation'],
    // ['GS Compassion', 'gs/compassion'],
    // ['GS Noah, Bible Patriarch', 'gs/noah-bible-patriarch'],
    // ['GS Sanctification', 'gs/sanctification'],
    // ['GS Lamb of God', 'gs/lamb-of-god'],
    // ['GS Earth—Cleansing of the earth', 'gs/earth/cleansing-of-the-earth'],
    // ['GS Filth, Filthiness', 'gs/filth-filthiness'],
    // ['GS Messiah', 'gs/messiah'],
    // ['GS Rock', 'gs/rock'],
    // ['GS Music', 'gs/music'],
    // ['GS Son of Man', 'gs/son-of-man'],
    // ['GS Crucifixion', 'gs/crucifixion'],
    // ['GS Resurrection', 'gs/resurrection'],
    // ['GS Crown', 'gs/crown'],
    // ['GS Exaltation', 'gs/exaltation'],
    // ['GS Spirit', 'gs/spirit'],
    // ['GS Last Days, Latter Days', 'gs/last-days-latter-days'],
    // ['GS Earth—Final state of the earth', 'gs/earth/final-state-of-the-earth'],
    // ['GS Veil', 'gs/veil'],
    // ['GS Restoration of the Gospel', 'gs/restoration-of-the-gospel'],
    // ['GS Book of Mormon', 'gs/book-of-mormon'],
    // ['GS Testimony', 'gs/testimony'],
    // ['GS Resurrection', 'gs/resurrection'],
    // ['GS Israel—The gathering of Israel', 'gs/israel/the-gathering-of-israel'],
    // ['GS New Jerusalem', 'gs/new-jerusalem'],
    // ['GS Millennium', 'gs/millennium'],
    // ['GS Second Coming of Jesus Christ', 'gs/second-coming-of-jesus-christ'],
    // ['GS Judgment, the Last', 'gs/judgment-the-last'],
    // ['GS Joy', 'gs/joy'],
    // ['GS Walk, Walk with God', 'gs/walk-walk-with-god'],
    // ['TG Famine', 'tg/famine'],
    // ['TG Curse', 'tg/curse'],
    // ['TG Curse', 'tg/curse'],
    // ['TG Obedience', 'tg/obedience'],
    // ['TG Sons and Daughters of God', 'tg/sons-and-daughters-of-god'],
    // ['TG Marriage, Interfaith', 'tg/marriage-interfaith'],
    // ['TG Marriage, Marry', 'tg/marriage-marry'],
    // ['TG Disobedience', 'tg/disobedience'],
    // ['TG God, Access to', 'tg/god-access-to'],
    // ['TG Flesh and Blood', 'tg/flesh-and-blood'],
    // ['TG Priesthood, Power of', 'tg/priesthood-power-of'],
    // ['TG Priesthood, Ordination', 'tg/priesthood-ordination'],
    // ['TG Priesthood, Melchizedek', 'tg/priesthood-melchizedek'],
    // ['TG Missionary Work', 'tg/missionary-work'],
    // ['TG Repent', 'tg/repent'],
    // ['TG Disobedience', 'tg/disobedience'],
    // ['TG Preaching', 'tg/preaching'],
    // ['TG Baptism, Qualifications for', 'tg/baptism-qualifications-for'],
    // ['TG Baptism, Essential', 'tg/baptism-essential'],
    // ['TG Earth, Cleansing of', 'tg/earth-cleansing-of'],
    // ['TG Grace', 'tg/grace'],
    // ['TG Walking with God', 'tg/walking-with-god'],
    // ['GS Methuselah', 'gs/methuselah'],
    // ['GS Noah, Bible Patriarch', 'gs/noah-bible-patriarch'],
    // ['GS Japheth', 'gs/japheth'],
    // ['GS Shem', 'gs/shem'],
    // ['GS Ham', 'gs/ham'],
    // ['GS Gabriel', 'gs/gabriel'],
    // ['GS Obedience, Obedient, Obey', 'gs/obedience-obedient-obey'],
    // ['GS Sons and Daughters of God', 'gs/sons-and-daughters-of-god'],
    // [
    //   'GS Marriage, Marry—Interfaith marriage',
    //   'gs/marriage-marry/interfaith-marriage'
    // ],
    // ['GS Flesh', 'gs/flesh'],
    // ['GS Power', 'gs/power'],
    // ['GS Ordain, Ordination', 'gs/ordain-ordination'],
    // ['GS Melchizedek Priesthood', 'gs/melchizedek-priesthood'],
    // ['GS Missionary Work', 'gs/missionary-work'],
    // ['GS Repent, Repentance', 'gs/repent-repentance'],
    // ['GS Thoughts', 'gs/thoughts'],
    // ['GS Preach', 'gs/preach'],
    // ['GS Belief, Believe', 'gs/belief-believe'],
    // [
    //   'GS Baptism, Baptize—Qualifications for baptism',
    //   'gs/baptism-baptize/qualifications-for-baptism'
    // ],
    // ['GS Earth—Cleansing of the earth', 'gs/earth/cleansing-of-the-earth'],
    // ['GS Grace', 'gs/grace'],
    // ['GS Walk, Walk with God', 'gs/walk-walk-with-god'],
    // ['TG Happiness', 'tg/happiness'],
    // ['TG Priesthood, Qualifying for', 'tg/priesthood-qualifying-for'],
    // ['TG Rest', 'tg/rest'],
    // ['TG Righteousness', 'tg/righteousness'],
    //    [
    //      'TG God, the Standard of Righteousness',
    //      'tg/god-the-standard-of-righteousness'
    //    ],
    //    [
    //      'TG High Priest, Melchizedek Priesthood',
    //      'tg/high-priest-melchizedek-priesthood'
    //    ],
    // ['TG Priesthood, History of', 'tg/priesthood-history-of'],
    // ['TG Priesthood, Melchizedek', 'tg/priesthood-melchizedek'],
    // ['TG Authority', 'tg/authority'],
    // ['TG Patriarch', 'tg/patriarch'],
    // ['TG Firstborn', 'tg/firstborn'],
    // ['TG Adam', 'tg/adam'],
    // ['TG Birthright', 'tg/birthright'],
    // ['TG Heathen', 'tg/heathen'],
    // ['TG Hardheartedness', 'tg/hardheartedness'],
    // ['TG Heathen', 'tg/heathen'],
    // ['TG False Priesthoods', 'tg/false-priesthoods'],
    // ['TG Jesus Christ, Jehovah', 'tg/jesus-christ-jehovah'],
    // ['TG Promised Lands', 'tg/promised-lands'],
    // ['TG Worship', 'tg/worship'],
    // ['TG Governments', 'tg/governments'],
    // ['TG Order', 'tg/order'],
    // ['TG Blessing', 'tg/blessing'],
    // ['TG Priesthood, Qualifying for', 'tg/priesthood-qualifying-for'],
    // ['TG Unrighteous Dominion', 'tg/unrighteous-dominion'],
    // ['TG Scriptures, Writing of', 'tg/scriptures-writing-of'],
    // ['TG Famine', 'tg/famine'],
    // ['TG Record Keeping', 'tg/record-keeping'],
    // ['TG Scriptures, Preservation of', 'tg/scriptures-preservation-of'],
    // ['TG Astronomy', 'tg/astronomy'],
    // ['TG Book of Remembrance', 'tg/book-of-remembrance'],
    // ['GS Ur', 'gs/ur'],
    // ['GS Abraham', 'gs/abraham'],
    // ['GS Joy', 'gs/joy'],
    // ['GS Rest', 'gs/rest'],
    // ['GS Righteous, Righteousness', 'gs/righteous-righteousness'],
    // ['GS Knowledge', 'gs/knowledge'],
    // ['GS High Priest', 'gs/high-priest'],
    // ['GS Melchizedek Priesthood', 'gs/melchizedek-priesthood'],
    // ['GS Firstborn', 'gs/firstborn'],
    // ['GS Adam', 'gs/adam'],
    // ['GS Birthright', 'gs/birthright'],
    // ['GS Idolatry', 'gs/idolatry'],
    // ['GS Ham', 'gs/ham'],
    // ['GS Jehovah', 'gs/jehovah'],
    // ['GS Promised Land', 'gs/promised-land'],
    // ['GS Priesthood', 'gs/priesthood'],
    // ['GS Canaan, Canaanite', 'gs/canaan-canaanite'],
    // ['GS Egypt', 'gs/egypt'],
    // ['GS Bless, Blessed, Blessing', 'gs/bless-blessed-blessing'],
    // ['GS Priesthood', 'gs/priesthood'],
    // ['GS Book of Remembrance', 'gs/book-of-remembrance'],
    // ['TG God, Manifestations of', 'tg/god-manifestations-of'],
    //    [
    //      'TG Jesus Christ, Appearances, Antemortal',
    //      'tg/jesus-christ-appearances-antemortal'
    //    ],
    // ['TG Delegation of Responsibility', 'tg/delegation-of-responsibility'],
    // ['TG Israel, Land of', 'tg/israel-land-of'],
    // ['TG God, Foreknowledge of', 'tg/god-foreknowledge-of'],
    // ['TG God, Omniscience of', 'tg/god-omniscience-of'],
    // ['TG Seed of Abraham', 'tg/seed-of-abraham'],
    // ['TG Israel, Blessings of', 'tg/israel-blessings-of'],
    // ['TG Patriarch', 'tg/patriarch'],
    // ['TG Israel, Blessings of', 'tg/israel-blessings-of'],
    // ['TG Curse', 'tg/curse'],
    // ['TG Birthright', 'tg/birthright'],
    // ['TG Israel, Mission of', 'tg/israel-mission-of'],
    // ['TG Priesthood, Melchizedek', 'tg/priesthood-melchizedek'],
    // ['TG Conversion', 'tg/conversion'],
    // ['TG Eternity', 'tg/eternity'],
    // ['TG Rock', 'tg/rock'],
    // ['TG Sacrifice', 'tg/sacrifice'],
    // ['TG Promised Lands', 'tg/promised-lands'],
    // ['GS Sarah', 'gs/sarah'],
    // ['GS Lot', 'gs/lot'],
    // [
    //   'GS Jesus Christ—Premortal existence of Christ',
    //   'gs/jesus-christ/premortal-existence-of-christ'
    // ],
    // ['GS Promised Land', 'gs/promised-land'],
    // ['GS Jehovah', 'gs/jehovah'],
    // ['GS Omniscient', 'gs/omniscient'],
    // ['GS Abraham—The seed of Abraham', 'gs/abraham/the-seed-of-abraham'],
    // ['GS Melchizedek Priesthood', 'gs/melchizedek-priesthood'],
    // ['GS Patriarch, Patriarchal', 'gs/patriarch-patriarchal'],
    // ['GS Abrahamic Covenant', 'gs/abrahamic-covenant'],
    // ['GS Birthright', 'gs/birthright'],
    // ['GS Israel', 'gs/israel'],
    // ['GS Priesthood', 'gs/priesthood'],
    // ['GS Sarah', 'gs/sarah'],
    // ['GS Ur', 'gs/ur'],
    // ['GS Conversion, Convert', 'gs/conversion-convert'],
    // ['GS Canaan, Canaanite', 'gs/canaan-canaanite'],
    // ['GS Rock', 'gs/rock'],
    // ['GS Altar', 'gs/altar'],
    // ['GS Sacrifice', 'gs/sacrifice'],
    // ['GS Promised Land', 'gs/promised-land'],
    // ['GS Bethel', 'gs/bethel'],
    // ['TG Urim and Thummim', 'tg/urim-and-thummim'],
    // ['TG Astronomy', 'tg/astronomy'],
    // ['TG Time', 'tg/time'],
    // ['TG Astronomy', 'tg/astronomy'],
    // ['TG Order', 'tg/order'],
    // ['TG God, Access to', 'tg/god-access-to'],
    // ['TG God, Manifestations of', 'tg/god-manifestations-of'],
    // ['TG God, Privilege of Seeing', 'tg/god-privilege-of-seeing'],
    // ['TG Guidance, Divine', 'tg/guidance-divine'],
    // ['TG Spirit Body', 'tg/spirit-body'],
    // ['TG Spirit Creation', 'tg/spirit-creation'],
    // ['TG God, Intelligence of', 'tg/god-intelligence-of'],
    // ['TG God, Omniscience of', 'tg/god-omniscience-of'],
    // ['TG Intelligence', 'tg/intelligence'],
    // ['TG God, Perfection of', 'tg/god-perfection-of'],
    // ['TG Kingdom of God, in Heaven', 'tg/kingdom-of-god-in-heaven'],
    // ['TG Council in Heaven', 'tg/council-in-heaven'],
    // ['TG Intelligence', 'tg/intelligence'],
    // ['TG Man, Antemortal Existence of', 'tg/man-antemortal-existence-of'],
    //    [
    //      'TG Man, a Spirit Child of Heavenly Father',
    //      'tg/man-a-spirit-child-of-heavenly-father'
    //    ],
    // ['TG Spirit Creation', 'tg/spirit-creation'],
    // ['TG Election', 'tg/election'],
    // ['TG Foreordination', 'tg/foreordination'],
    // ['TG Jesus Christ, Firstborn', 'tg/jesus-christ-firstborn'],
    // ['TG Jesus Christ, Creator', 'tg/jesus-christ-creator'],
    // ['TG Earth, Purpose of', 'tg/earth-purpose-of'],
    // ['TG Agency', 'tg/agency'],
    // ['TG Salvation, Plan of', 'tg/salvation-plan-of'],
    // ['TG Test', 'tg/test'],
    // ['TG Obedience', 'tg/obedience'],
    // ['TG Dependability', 'tg/dependability'],
    // ['TG Mortality', 'tg/mortality'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Reward', 'tg/reward'],
    // ['TG God the Father, Elohim', 'tg/god-the-father-elohim'],
    // ['TG Jesus Christ, Authority of', 'tg/jesus-christ-authority-of'],
    // ['TG Jesus Christ, Foreordained', 'tg/jesus-christ-foreordained'],
    //    [
    //      'TG Jesus Christ, Messenger of the Covenant',
    //      'tg/jesus-christ-messenger-of-the-covenant'
    //    ],
    // ['TG Jesus Christ, Messiah', 'tg/jesus-christ-messiah'],
    // ['TG Jesus Christ, Mission of', 'tg/jesus-christ-mission-of'],
    // ['TG Devil', 'tg/devil'],
    // ['TG Sons of Perdition', 'tg/sons-of-perdition'],
    // ['GS Urim and Thummim', 'gs/urim-and-thummim'],
    // ['GS Kolob', 'gs/kolob'],
    // ['GS Omniscient', 'gs/omniscient'],
    // ['GS Wisdom', 'gs/wisdom'],
    // ['GS Intelligence, Intelligences', 'gs/intelligence-intelligences'],
    // ['GS Council in Heaven', 'gs/council-in-heaven'],
    // ['GS Premortal Life', 'gs/premortal-life'],
    // ['GS Choose, Chose, Chosen (verb)', 'gs/choose-chose-chosen-verb'],
    // ['GS Foreordination', 'gs/foreordination'],
    // ['GS Firstborn', 'gs/firstborn'],
    // ['GS Create, Creation', 'gs/create-creation'],
    // ['GS Earth—Created for man', 'gs/earth/created-for-man'],
    // ['GS Agency', 'gs/agency'],
    // ['GS Plan of Redemption', 'gs/plan-of-redemption'],
    // ['GS Obedience, Obedient, Obey', 'gs/obedience-obedient-obey'],
    // ['GS Mortal, Mortality', 'gs/mortal-mortality'],
    // ['GS Glory', 'gs/glory'],
    // ['GS God, Godhead—God the Father', 'gs/god-godhead/god-the-father'],
    // ['GS Jesus Christ', 'gs/jesus-christ'],
    // ['GS Son of Man', 'gs/son-of-man'],
    // ['GS Devil', 'gs/devil'],
    // ['GS Sons of Perdition', 'gs/sons-of-perdition'],
    // ['TG Jesus Christ, Creator', 'tg/jesus-christ-creator'],
    // ['TG Darkness, Physical', 'tg/darkness-physical'],
    // ['TG Darkness, Physical', 'tg/darkness-physical'],
    // ['TG Order', 'tg/order'],
    // ['TG Counsel', 'tg/counsel'],
    // ['TG Man, Physical Creation of', 'tg/man-physical-creation-of'],
    // ['TG God, Body of, Corporeal Nature', 'tg/god-body-of-corporeal-nature'],
    // ['GS Create, Creation', 'gs/create-creation'],
    // ['GS Heaven', 'gs/heaven'],
    // ['GS God, Godhead', 'gs/god-godhead'],
    // ['GS Counsel (noun)', 'gs/counsel-noun'],
    // ['GS Man, Men', 'gs/man-men'],
    // ['TG Rest', 'tg/rest'],
    // ['TG Sabbath', 'tg/sabbath'],
    // ['TG Spirit Creation', 'tg/spirit-creation'],
    // ['TG Man, Antemortal Existence of', 'tg/man-antemortal-existence-of'],
    // ['TG Spirit Body', 'tg/spirit-body'],
    // ['TG Soul', 'tg/soul'],
    // ['TG Eden', 'tg/eden'],
    // ['TG Time', 'tg/time'],
    // ['TG Woman', 'tg/woman'],
    // ['TG Divorce', 'tg/divorce'],
    // ['TG Marriage, Celestial', 'tg/marriage-celestial'],
    // ['TG Shame', 'tg/shame'],
    // ['TG Adam', 'tg/adam'],
    // ['TG Language', 'tg/language'],
    // ['GS Sabbath Day', 'gs/sabbath-day'],
    // ['GS Spirit Creation', 'gs/spirit-creation'],
    // ['GS Premortal Life', 'gs/premortal-life'],
    // ['GS Spirit', 'gs/spirit'],
    // ['GS Soul', 'gs/soul'],
    // ['GS Eden', 'gs/eden'],
    // ['GS Tree of Life', 'gs/tree-of-life'],
    // ['GS Kolob', 'gs/kolob'],
    // ['GS Adam', 'gs/adam'],
    // ['GS Eve', 'gs/eve'],
    // ['GS Marriage, Marry', 'gs/marriage-marry'],
    //    [
    //      'TG Jesus Christ, Relationships with the Father',
    //      'tg/jesus-christ-relationships-with-the-father'
    //    ],
    // ['TG Last Days', 'tg/last-days'],
    // ['TG Jesus Christ, Second Coming', 'tg/jesus-christ-second-coming'],
    // ['TG World, End of', 'tg/world-end-of'],
    // ['TG False Christs', 'tg/false-christs'],
    // ['TG Hate', 'tg/hate'],
    // ['TG Malice', 'tg/malice'],
    // ['TG Offense', 'tg/offense'],
    // ['TG False Prophets', 'tg/false-prophets'],
    // ['TG Abomination of Desolation', 'tg/abomination-of-desolation'],
    // ['TG Jerusalem', 'tg/jerusalem'],
    // ['TG Israel, Judah, People of', 'tg/israel-judah-people-of'],
    // ['TG False Christs', 'tg/false-christs'],
    // ['TG Nations', 'tg/nations'],
    // ['TG Tribulation', 'tg/tribulation'],
    // ['TG Mourning', 'tg/mourning'],
    // ['TG Millennium', 'tg/millennium'],
    // ['TG Scriptures, Study of', 'tg/scriptures-study-of'],
    // ['TG Study', 'tg/study'],
    // ['TG Treasure', 'tg/treasure'],
    // ['TG Jesus Christ, Second Coming', 'tg/jesus-christ-second-coming'],
    // ['TG Israel, Remnant of', 'tg/israel-remnant-of'],
    // ['TG Flood', 'tg/flood'],
    // ['TG Apathy', 'tg/apathy'],
    // ['TG Earth, Cleansing of', 'tg/earth-cleansing-of'],
    // ['TG Watch', 'tg/watch'],
    // ['TG Procrastination', 'tg/procrastination'],
    // ['TG Trustworthiness', 'tg/trustworthiness'],
    //    [
    //      'TG Millennium, Preparing a People for',
    //      'tg/millennium-preparing-a-people-for'
    //    ],
    // ['TG World, End of', 'tg/world-end-of'],
    // ['GS God, Godhead', 'gs/god-godhead'],
    // ['GS Olives, Mount of', 'gs/olives-mount-of'],
    // ['GS Last Days, Latter Days', 'gs/last-days-latter-days'],
    // ['GS Signs of the Times', 'gs/signs-of-the-times'],
    // ['GS Second Coming of Jesus Christ', 'gs/second-coming-of-jesus-christ'],
    // ['GS World—End of the world', 'gs/world/end-of-the-world'],
    // ['GS Wicked, Wickedness', 'gs/wicked-wickedness'],
    // ['GS Persecute, Persecution', 'gs/persecute-persecution'],
    // ['GS Daniel', 'gs/daniel'],
    // ['GS Jerusalem', 'gs/jerusalem'],
    // ['GS Jews', 'gs/jews'],
    // ['GS Elect', 'gs/elect'],
    // ['GS Israel—The gathering of Israel', 'gs/israel/the-gathering-of-israel'],
    // ['GS Second Coming of Jesus Christ', 'gs/second-coming-of-jesus-christ'],
    // ['GS Scriptures', 'gs/scriptures'],
    // ['GS Israel—The gathering of Israel', 'gs/israel/the-gathering-of-israel'],
    // ['GS Flood at Noah’s Time', 'gs/flood-at-noahs-time'],
    // ['GS Last Days, Latter Days', 'gs/last-days-latter-days'],
    // ['GS Watch, Watchmen', 'gs/watch-watchmen'],
    // ['GS Trust', 'gs/trust'],
    // ['GS World—End of the world', 'gs/world/end-of-the-world'],
    // ['TG Restoration of the Gospel', 'tg/restoration-of-the-gospel'],
    // ['TG Joseph Smith', 'tg/joseph-smith'],
    // ['TG Guile', 'tg/guile'],
    // ['TG Hypocrisy', 'tg/hypocrisy'],
    // ['TG Strife', 'tg/strife'],
    // ['TG Truth', 'tg/truth'],
    // ['TG Guidance, Divine', 'tg/guidance-divine'],
    // ['TG Communication', 'tg/communication'],
    // ['TG Beauty', 'tg/beauty'],
    // ['TG Prayer', 'tg/prayer'],
    // ['TG Darkness, Physical', 'tg/darkness-physical'],
    // ['TG Despair', 'tg/despair'],
    // ['TG Deliver', 'tg/deliver'],
    // ['TG God, Privilege of Seeing', 'tg/god-privilege-of-seeing'],
    // ['TG Vision', 'tg/vision'],
    // ['TG God, Manifestations of', 'tg/god-manifestations-of'],
    // ['TG Godhead', 'tg/godhead'],
    // ['TG God the Father, Elohim', 'tg/god-the-father-elohim'],
    //    [
    //      'TG Jesus Christ, Appearances, Postmortal',
    //      'tg/jesus-christ-appearances-postmortal'
    //    ],
    // ['TG Restoration of the Gospel', 'tg/restoration-of-the-gospel'],
    // ['TG Revelation', 'tg/revelation'],
    // ['TG Jesus Christ, Glory of', 'tg/jesus-christ-glory-of'],
    // ['TG Witness of the Father', 'tg/witness-of-the-father'],
    // ['TG Jesus Christ, Divine Sonship', 'tg/jesus-christ-divine-sonship'],
    //    [
    //      'TG Apostasy of the Early Christian Church',
    //      'tg/apostasy-of-the-early-christian-church'
    //    ]
    // ['TG False Prophets', 'tg/false-prophets'],
    // ['TG False Doctrine', 'tg/false-doctrine'],
    // ['TG Apostasy of Individuals', 'tg/apostasy-of-individuals'],
    // ['TG Hardheartedness', 'tg/hardheartedness'],
    // ['TG Hypocrisy', 'tg/hypocrisy'],
    // ['TG Family, Love within', 'tg/family-love-within'],
    // ['TG Devil', 'tg/devil'],
    // ['TG Revelation', 'tg/revelation'],
    // ['TG Industry', 'tg/industry'],
    // ['TG Malice', 'tg/malice'],
    // ['TG Persecution', 'tg/persecution'],
    // ['TG Reviling', 'tg/reviling'],
    // ['TG Vision', 'tg/vision'],
    // ['TG Hate', 'tg/hate'],
    // ['TG Adversity', 'tg/adversity'],
    // ['TG Injustice', 'tg/injustice'],
    // ['TG Courage', 'tg/courage'],
    // ['TG Honesty', 'tg/honesty'],
    // ['TG Integrity', 'tg/integrity'],
    // ['TG Friendship', 'tg/friendship'],
    // ['TG Temptation', 'tg/temptation'],
    // ['TG Levity', 'tg/levity'],
    // ['TG Called of God', 'tg/called-of-god'],
    // ['TG Cheerful', 'tg/cheerful'],
    // ['TG Prayer', 'tg/prayer'],
    // ['TG Angels', 'tg/angels'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Book of Mormon', 'tg/book-of-mormon'],
    // ['TG Scriptures, Preservation of', 'tg/scriptures-preservation-of'],
    // ['TG Restoration of the Gospel', 'tg/restoration-of-the-gospel'],
    // ['TG Urim and Thummim', 'tg/urim-and-thummim'],
    // ['TG Day of the Lord', 'tg/day-of-the-lord'],
    // ['TG Earth, Cleansing of', 'tg/earth-cleansing-of'],
    // ['TG World, End of', 'tg/world-end-of'],
    // ['TG Priesthood', 'tg/priesthood'],
    // ['TG Priesthood, Keys of', 'tg/priesthood-keys-of'],
    // ['TG Millennium', 'tg/millennium'],
    // ['TG Genealogy and Temple Work', 'tg/genealogy-and-temple-work'],
    // ['TG Salvation for the Dead', 'tg/salvation-for-the-dead'],
    // ['TG Gentiles', 'tg/gentiles'],
    // ['TG Mind', 'tg/mind'],
    // ['TG Meditation', 'tg/meditation'],
    // ['TG Judgment', 'tg/judgment'],
    // ['TG Famine', 'tg/famine'],
    // ['TG Temptation', 'tg/temptation'],
    // ['TG Sacrilege', 'tg/sacrilege'],
    // ['TG Meditation', 'tg/meditation'],
    // ['TG Strength', 'tg/strength'],
    // ['TG Family, Love within', 'tg/family-love-within'],
    // ['TG Honoring Father and Mother', 'tg/honoring-father-and-mother'],
    // ['TG Counsel', 'tg/counsel'],
    // ['TG Urim and Thummim', 'tg/urim-and-thummim'],
    // ['TG Kingdom of God, on Earth', 'tg/kingdom-of-god-on-earth'],
    // ['TG Industry', 'tg/industry'],
    // ['TG Work, Value of', 'tg/work-value-of'],
    // ['TG Affliction', 'tg/affliction'],
    // ['TG Hate', 'tg/hate'],
    // ['TG Persecution', 'tg/persecution'],
    // ['TG Industry', 'tg/industry'],
    // ['TG Dependability', 'tg/dependability'],
    // ['TG Trustworthiness', 'tg/trustworthiness'],
    // ['TG Scriptures, Preservation of', 'tg/scriptures-preservation-of'],
    // ['TG Stealing', 'tg/stealing'],
    // ['TG Injustice', 'tg/injustice'],
    // ['TG Urim and Thummim', 'tg/urim-and-thummim'],
    // ['TG Angels, Ministering', 'tg/angels-ministering'],
    // ['TG Scriptures, Writing of', 'tg/scriptures-writing-of'],
    // ['TG Baptism', 'tg/baptism'],
    // ['TG Baptism, Essential', 'tg/baptism-essential'],
    // ['TG Baptism, Immersion', 'tg/baptism-immersion'],
    // ['TG Remission of Sins', 'tg/remission-of-sins'],
    // ['TG Hands, Laying on of', 'tg/hands-laying-on-of'],
    // ['TG Priesthood, Authority', 'tg/priesthood-authority'],
    // ['TG Priesthood, History of', 'tg/priesthood-history-of'],
    // ['TG Restoration of the Gospel', 'tg/restoration-of-the-gospel'],
    // ['TG Priesthood, Aaronic', 'tg/priesthood-aaronic'],
    // ['TG Baptism', 'tg/baptism'],
    // ['TG Righteousness', 'tg/righteousness'],
    // ['TG Priesthood, Keys of', 'tg/priesthood-keys-of'],
    // ['TG Priesthood, Melchizedek', 'tg/priesthood-melchizedek'],
    // ['TG Elder', 'tg/elder'],
    // ['TG Holy Ghost, Gifts of', 'tg/holy-ghost-gifts-of'],
    // ['TG Holy Ghost, Mission of', 'tg/holy-ghost-mission-of'],
    // ['TG Mysteries of Godliness', 'tg/mysteries-of-godliness'],
    // ['TG Friendship', 'tg/friendship'],
    // ['GS Restoration of the Gospel', 'gs/restoration-of-the-gospel'],
    // [
    //   'GS Church of Jesus Christ of Latter-day Saints, The',
    //   'gs/church-of-jesus-christ-of-latter-day-saints-the'
    // ],
    // ['GS Smith, Joseph, Jr.', 'gs/smith-joseph-jr'],
    // ['GS Smith, Joseph, Sr.', 'gs/smith-joseph-sr'],
    // ['GS Smith, Lucy Mack', 'gs/smith-lucy-mack'],
    // ['GS Smith, Hyrum', 'gs/smith-hyrum'],
    // ['GS Smith, SamuelH.', 'gs/smith-samuel-h'],
    // ['GS Contention', 'gs/contention'],
    // ['GS Truth', 'gs/truth'],
    // ['GS Bible', 'gs/bible'],
    // ['GS Prayer', 'gs/prayer'],
    // ['GS Prayer', 'gs/prayer'],
    // ['GS Vision', 'gs/vision'],
    // ['GS God, Godhead', 'gs/god-godhead'],
    // ['GS Glory', 'gs/glory'],
    // ['GS Jesus Christ', 'gs/jesus-christ'],
    // [
    //   'GS Apostasy—Apostasy of the early Christian church',
    //   'gs/apostasy/apostasy-of-the-early-christian-church'
    // ],
    // ['GS Apostasy—General apostasy', 'gs/apostasy/general-apostasy'],
    // ['GS Devil', 'gs/devil'],
    // ['GS Adversity', 'gs/adversity'],
    // ['GS First Vision', 'gs/first-vision'],
    // ['GS Vision', 'gs/vision'],
    // ['GS Revelation', 'gs/revelation'],
    // ['GS Persecute, Persecution', 'gs/persecute-persecution'],
    // ['GS Paul', 'gs/paul'],
    // ['GS Courage, Courageous', 'gs/courage-courageous'],
    // ['GS Integrity', 'gs/integrity'],
    // ['GS Tempt, Temptation', 'gs/tempt-temptation'],
    // ['GS Call, Called of God, Calling', 'gs/call-called-of-god-calling'],
    // ['GS Prayer', 'gs/prayer'],
    // ['GS Angels', 'gs/angels'],
    // ['GS Moroni, Son of Mormon', 'gs/moroni-son-of-mormon'],
    // ['GS Glory', 'gs/glory'],
    // ['GS Book of Mormon', 'gs/book-of-mormon'],
    // ['GS Gold Plates', 'gs/gold-plates'],
    // ['GS Restoration of the Gospel', 'gs/restoration-of-the-gospel'],
    // ['GS Breastplates', 'gs/breastplates'],
    // ['GS Urim and Thummim', 'gs/urim-and-thummim'],
    // ['GS Seer', 'gs/seer'],
    // ['GS Old Testament', 'gs/old-testament'],
    // ['GS Malachi', 'gs/malachi'],
    // ['GS Second Coming of Jesus Christ', 'gs/second-coming-of-jesus-christ'],
    // ['GS Earth—Cleansing of the earth', 'gs/earth/cleansing-of-the-earth'],
    // ['GS World—End of the world', 'gs/world/end-of-the-world'],
    // ['GS Keys of the Priesthood', 'gs/keys-of-the-priesthood'],
    // ['GS Priesthood', 'gs/priesthood'],
    // ['GS Elijah', 'gs/elijah'],
    // ['GS Genealogy', 'gs/genealogy'],
    // ['GS Salvation for the Dead', 'gs/salvation-for-the-dead'],
    // ['GS Gentiles', 'gs/gentiles'],
    // ['GS Mind', 'gs/mind'],
    // ['GS Ponder', 'gs/ponder'],
    // ['GS Devil', 'gs/devil'],
    // ['GS Tempt, Temptation', 'gs/tempt-temptation'],
    // ['GS Smith, Joseph, Sr.', 'gs/smith-joseph-sr'],
    // ['GS Cumorah, Hill', 'gs/cumorah-hill'],
    // ['GS Gold Plates', 'gs/gold-plates'],
    // ['GS Urim and Thummim', 'gs/urim-and-thummim'],
    // ['GS Breastplates', 'gs/breastplates'],
    // [
    //   'GS Kingdom of God or Kingdom of Heaven',
    //   'gs/kingdom-of-god-or-kingdom-of-heaven'
    // ],
    // ['GS Smith, Emma Hale', 'gs/smith-emma-hale'],
    // ['GS Persecute, Persecution', 'gs/persecute-persecution'],
    // [
    //   'GS Scriptures—Scriptures to be preserved',
    //   'gs/scriptures/scriptures-to-be-preserved'
    // ],
    // ['GS Harris, Martin', 'gs/harris-martin'],
    // ['GS Urim and Thummim', 'gs/urim-and-thummim'],
    // ['GS Angels', 'gs/angels'],
    // ['GS Cowdery, Oliver', 'gs/cowdery-oliver'],
    // ['GS Baptism, Baptize', 'gs/baptism-baptize'],
    // ['GS Remission of Sins', 'gs/remission-of-sins'],
    // ['GS John the Baptist', 'gs/john-the-baptist'],
    // ['GS Hands, Laying on of', 'gs/hands-laying-on-of'],
    // ['GS Authority', 'gs/authority'],
    // ['GS Ordain, Ordination', 'gs/ordain-ordination'],
    // ['GS Aaronic Priesthood', 'gs/aaronic-priesthood'],
    // ['GS Levi—The tribe of Levi', 'gs/levi/the-tribe-of-levi'],
    // ['GS Gift of the Holy Ghost', 'gs/gift-of-the-holy-ghost'],
    // ['GS John the Baptist', 'gs/john-the-baptist'],
    // ['GS Peter', 'gs/peter'],
    // ['GS James, Son of Zebedee', 'gs/james-son-of-zebedee'],
    // ['GS John, Son of Zebedee', 'gs/john-son-of-zebedee'],
    // ['GS Keys of the Priesthood', 'gs/keys-of-the-priesthood'],
    // ['GS Melchizedek Priesthood', 'gs/melchizedek-priesthood'],
    // ['GS Elder', 'gs/elder'],
    // ['GS Holy Ghost', 'gs/holy-ghost'],
    // ['GS Prophecy, Prophesy', 'gs/prophecy-prophesy'],
    // ['GS Understanding', 'gs/understanding'],
    // ['TG Believe', 'tg/believe'],
    // ['TG Godhead', 'tg/godhead'],
    // ['TG God the Father, Elohim', 'tg/god-the-father-elohim'],
    // ['TG Jesus Christ, Divine Sonship', 'tg/jesus-christ-divine-sonship'],
    // ['TG Holy Ghost', 'tg/holy-ghost'],
    // ['TG Punish', 'tg/punish'],
    // ['TG Accountability', 'tg/accountability'],
    // ['TG Agency', 'tg/agency'],
    // ['TG Fall of Man', 'tg/fall-of-man'],
    // ['TG Jesus Christ, Atonement through', 'tg/jesus-christ-atonement-through'],
    // ['TG Salvation', 'tg/salvation'],
    // ['TG Ordinance', 'tg/ordinance'],
    // ['TG Baptism, Qualifications for', 'tg/baptism-qualifications-for'],
    // ['TG Faith', 'tg/faith'],
    // ['TG Repent', 'tg/repent'],
    // ['TG Baptism', 'tg/baptism'],
    // ['TG Baptism, Immersion', 'tg/baptism-immersion'],
    // ['TG Remission of Sins', 'tg/remission-of-sins'],
    // ['TG Hands, Laying on of', 'tg/hands-laying-on-of'],
    // ['TG Holy Ghost, Gift of', 'tg/holy-ghost-gift-of'],
    // ['TG Called of God', 'tg/called-of-god'],
    // ['TG Priesthood, Qualifying for', 'tg/priesthood-qualifying-for'],
    // ['TG Prophecy', 'tg/prophecy'],
    // ['TG Hands, Laying on of', 'tg/hands-laying-on-of'],
    // ['TG Authority', 'tg/authority'],
    // ['TG Priesthood, Authority', 'tg/priesthood-authority'],
    // ['TG Preaching', 'tg/preaching'],
    // ['TG Church Organization', 'tg/church-organization'],
    // ['TG Prophets, Mission of', 'tg/prophets-mission-of'],
    // ['TG Bishop', 'tg/bishop'],
    // ['TG Teacher', 'tg/teacher'],
    // ['TG Teacher, Aaronic Priesthood', 'tg/teacher-aaronic-priesthood'],
    // ['TG Patriarch', 'tg/patriarch'],
    // ['TG Holy Ghost, Gifts of', 'tg/holy-ghost-gifts-of'],
    // ['TG Language', 'tg/language'],
    // ['TG Prophecy', 'tg/prophecy'],
    // ['TG Revelation', 'tg/revelation'],
    // ['TG Vision', 'tg/vision'],
    // ['TG Heal', 'tg/heal'],
    // ['TG Bible', 'tg/bible'],
    // ['TG Revelation', 'tg/revelation'],
    // ['TG Scriptures, Preservation of', 'tg/scriptures-preservation-of'],
    // ['TG Scriptures, Value of', 'tg/scriptures-value-of'],
    // ['TG Scriptures, Writing of', 'tg/scriptures-writing-of'],
    // ['TG Book of Mormon', 'tg/book-of-mormon'],
    // ['TG Revelation', 'tg/revelation'],
    // ['TG Scriptures to Come Forth', 'tg/scriptures-to-come-forth'],
    // ['TG Israel, Gathering of', 'tg/israel-gathering-of'],
    // ['TG Israel, Ten Lost Tribes of', 'tg/israel-ten-lost-tribes-of'],
    // ['TG Jerusalem, New', 'tg/jerusalem-new'],
    // ['TG Zion', 'tg/zion'],
    // ['TG Jesus Christ, Millennial Reign', 'tg/jesus-christ-millennial-reign'],
    // ['TG Earth, Cleansing of', 'tg/earth-cleansing-of'],
    // ['TG Earth, Renewal of', 'tg/earth-renewal-of'],
    // ['TG Eden', 'tg/eden'],
    // ['TG Paradise', 'tg/paradise'],
    // ['TG Glory', 'tg/glory'],
    // ['TG Agency', 'tg/agency'],
    // ['TG Conscience', 'tg/conscience'],
    // ['TG Worship', 'tg/worship'],
    // ['TG Citizenship', 'tg/citizenship'],
    // ['TG Governments', 'tg/governments'],
    // ['TG Kings, Earthly', 'tg/kings-earthly'],
    // ['TG Obedience', 'tg/obedience'],
    // ['TG Honesty', 'tg/honesty'],
    // ['TG Integrity', 'tg/integrity'],
    // ['TG Chastity', 'tg/chastity'],
    // ['TG Benevolence', 'tg/benevolence'],
    // ['TG Good Works', 'tg/good-works'],
    // ['TG Hope', 'tg/hope'],
    // ['TG Perseverance', 'tg/perseverance'],
    // ['TG Steadfastness', 'tg/steadfastness'],
    // ['TG Modesty', 'tg/modesty'],
    // ['TG Virtue', 'tg/virtue'],
    // ['TG Beauty', 'tg/beauty'],
    // ['GS Belief, Believe', 'gs/belief-believe'],
    // ['GS God, Godhead—God the Father', 'gs/god-godhead/god-the-father'],
    // ['GS God, Godhead—God the Son', 'gs/god-godhead/god-the-son'],
    // ['GS Jesus Christ', 'gs/jesus-christ'],
    // ['GS God, Godhead—God the Holy Ghost', 'gs/god-godhead/god-the-holy-ghost'],
    // ['GS Holy Ghost', 'gs/holy-ghost'],
    // [
    //   'GS Account, Accountable, Accountability',
    //   'gs/account-accountable-accountability'
    // ],
    // ['GS Agency', 'gs/agency'],
    // ['GS Fall of Adam and Eve', 'gs/fall-of-adam-and-eve'],
    // ['GS Atone, Atonement', 'gs/atone-atonement'],
    // ['GS Salvation', 'gs/salvation'],
    // ['GS Obedience, Obedient, Obey', 'gs/obedience-obedient-obey'],
    // ['GS Law', 'gs/law'],
    // ['GS Gospel', 'gs/gospel'],
    // ['GS Ordinances', 'gs/ordinances'],
    // ['GS Faith', 'gs/faith'],
    // ['GS Repent, Repentance', 'gs/repent-repentance'],
    // ['GS Baptism, Baptize', 'gs/baptism-baptize'],
    // ['GS Remission of Sins', 'gs/remission-of-sins'],
    // ['GS Hands, Laying on of', 'gs/hands-laying-on-of'],
    // ['GS Gift of the Holy Ghost', 'gs/gift-of-the-holy-ghost'],
    // ['GS Call, Called of God, Calling', 'gs/call-called-of-god-calling'],
    // ['GS Prophecy, Prophesy', 'gs/prophecy-prophesy'],
    // ['GS Hands, Laying on of', 'gs/hands-laying-on-of'],
    // ['GS Authority', 'gs/authority'],
    // ['GS Priesthood', 'gs/priesthood'],
    // ['GS Preach', 'gs/preach'],
    // [
    //   'GS Church, Signs of the True—Church organization',
    //   'gs/church-signs-of-the-true/church-organization'
    // ],
    // ['GS Apostle', 'gs/apostle'],
    // ['GS Prophet', 'gs/prophet'],
    // ['GS Bishop', 'gs/bishop'],
    // ['GS Evangelist', 'gs/evangelist'],
    // ['GS Patriarch, Patriarchal', 'gs/patriarch-patriarchal'],
    // ['GS Gifts of the Spirit', 'gs/gifts-of-the-spirit'],
    // ['GS Tongues, Gift of', 'gs/tongues-gift-of'],
    // ['GS Prophecy, Prophesy', 'gs/prophecy-prophesy'],
    // ['GS Revelation', 'gs/revelation'],
    // ['GS Vision', 'gs/vision'],
    // ['GS Heal, Healings', 'gs/heal-healings'],
    // ['GS Bible', 'gs/bible'],
    // ['GS Word of God', 'gs/word-of-god'],
    // ['GS Book of Mormon', 'gs/book-of-mormon'],
    // ['GS Revelation', 'gs/revelation'],
    // [
    //   'GS Scriptures—Scriptures prophesied to come forth',
    //   'gs/scriptures/scriptures-prophesied-to-come-forth'
    // ],
    // ['GS Israel—The gathering of Israel', 'gs/israel/the-gathering-of-israel'],
    // [
    //   'GS Israel—The ten lost tribes of Israel',
    //   'gs/israel/the-ten-lost-tribes-of-israel'
    // ],
    // ['GS New Jerusalem', 'gs/new-jerusalem'],
    // ['GS Zion', 'gs/zion'],
    // ['GS Millennium', 'gs/millennium'],
    // ['GS Earth—Cleansing of the earth', 'gs/earth/cleansing-of-the-earth'],
    // ['GS Paradise', 'gs/paradise'],
    // ['GS Glory', 'gs/glory'],
    // ['GS Agency', 'gs/agency'],
    // ['GS Conscience', 'gs/conscience'],
    // ['GS Worship', 'gs/worship'],
    // ['GS Law', 'gs/law'],
    // ['GS Honest, Honesty', 'gs/honest-honesty'],
    // ['GS Integrity', 'gs/integrity'],
    // ['GS Chastity', 'gs/chastity'],
    // ['GS Service', 'gs/service'],
    // ['GS Hope', 'gs/hope'],
    // ['GS Endure', 'gs/endure'],
    // ['GS Modesty', 'gs/modesty'],
    // ['GS Virtue', 'gs/virtue']
  ];
}
